blogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import BlogsConfig
from .views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogsConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('list', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import MailingConfig
from .views import MailingListView, MailingCreateView, ClientCreateView, MailingUpdateView, \
    MailingDeleteView, MailingDetailView, ClientListView, ClientDetailView, ClientUpdateView, ClientDeleteView, \
    IndexListView, MailingLogListView

app_name = MailingConfig.name

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('mailing_list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_detail/<int:pk>/', cache_page(60)(MailingDetailView.as_view()), name='mailing_detail'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_detail/<int:pk>/', cache_page(60)(ClientDetailView.as_view()), name='client_detail'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('mailing_log_list/', MailingLogListView.as_view(), name='mailing_log_list'),
    ]

mailing/models.py
from datetime import datetime
from django.db import models
from config import settings
from mailing.utils import NULLABLE


class Client(models.Model):
    email = models.EmailField(verbose_name='электронная почта', unique=True)
    fio = models.CharField(max_length=100, verbose_name='ФИО')
    comment = models.TextField(verbose_name='комментарий')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь', **NULLABLE)

    def __str__(self):
        return f'{self.email}  {self.fio}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Mailing(models.Model):
    CHOICES_STATUS = (
        ('created', 'создана'),
        ('running', 'запущена'),
        ('completed', 'завершена'),
    )
    CHOICES_TIME = (
        ('day', 'раз в день'),
        ('week', 'раз в неделю'),
        ('mon', 'раз в месяц'),
    )
    CHOICES_DAYWEEK = (
        ('0', 'понедельник'),
        ('1', 'вторник'),
        ('2', 'среда'),
        ('3', 'четверг'),
        ('4', 'пятница'),
        ('5', 'суббота'),
        ('6', 'вскресенье'),
    )

    name = models.CharField(max_length=100, verbose_name='тема письма')
    body = models.TextField(verbose_name='тело письма')
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, verbose_name='статус', default='created')
    time_start = models.TimeField(verbose_name='начало времени отправки',
                                  help_text='Введите время в формате ЧЧ:ММ через двоеточие. Начало времени отправки '
                                            'должно быть раньше окончания времени отправки ')
    time_end = models.TimeField(verbose_name='окончание времени отправки',
                                help_text='Введите время в формате ЧЧ:ММ через  двоеточие. Начало времени отправки '
                                            'должно быть раньше окончания времени отправки ')
    periodicity = models.CharField(max_length=20, choices=CHOICES_TIME, verbose_name='периодичность')
    day = models.IntegerField(verbose_name='день', **NULLABLE,
                              help_text='Введите число при периодичности раз в месяц. Число должно быть от 1 до 31')
    day_week = models.CharField(max_length=15, choices=CHOICES_DAYWEEK, verbose_name='день недели', **NULLABLE,
                                help_text='Выберите день недели при периодичности раз в неделю')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='активность рассылки')
    clients = models.ManyToManyField("Client", related_name='clients', verbose_name='клиенты')

    def __str__(self):
        return f'{self.name}, {self.body}'

    class Meta:
        verbose_name = 'письмо'
        verbose_name_plural = 'письма'
        ordering = ['name', ]


class MailingLog(models.Model):
    STATUS_CHOICES = (
        ('1', 'Успешно'),
        ('0', 'Неуспешно'),
    )

    time_try = models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, verbose_name='статус попытки')
    server_response = models.TextField(verbose_name='ответ почтового сервера', **NULLABLE)
    client = models.CharField(max_length=150, verbose_name='клиент', **NULLABLE)
    mailing_current = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return f'Лог: "{self.mailing_current}"'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'
        ordering = ['-time_try', ]

mailing/forms.py
from django import forms
from mailing.models import Mailing, Client
import datetime


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'clients':
                continue
            elif field_name == 'user':
                continue
            elif field_name == 'is_active':
                continue
            else:
                field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):
    clients = forms.ModelMultipleChoiceField(
        queryset=Client.objects.none(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Mailing
        exclude = ['user', 'is_active']

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(user=user)

    def clean_day(self):
        cleaned_data = self.cleaned_data['day']

        if 0 > cleaned_data > 31:
            raise forms.ValidationError('Число должно быть от 1 до 31')

        return cleaned_data


class MailingUpdateForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mailing
        exclude = ['is_active']

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(user=user)
        self.fields['user'].disabled = True


class MailingManagerUpdateForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mailing
        exclude = ['clients']

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].disabled = True
        self.fields['body'].disabled = True
        self.fields['status'].disabled = True
        self.fields['time_start'].disabled = True
        self.fields['time_end'].disabled = True
        self.fields['periodicity'].disabled = True
        self.fields['day'].disabled = True
        self.fields['day_week'].disabled = True
        self.fields['user'].disabled = True


class ClientForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        exclude = ('user',)

mailing/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.shortcuts import render, redirect
import random
from blogs.models import Blog
from mailing.forms import MailingForm, ClientForm, MailingUpdateForm, MailingManagerUpdateForm
from mailing.models import Mailing, Client, MailingLog
from apscheduler.schedulers.background import BackgroundScheduler
from django.core.management import call_command

from mailing.servises import mail_status_chenge


def mailing_start():
    return call_command('mailing_start')


scheduler = BackgroundScheduler()
scheduler.add_job(mailing_start, 'interval', seconds=600)
scheduler.add_job(mail_status_chenge, 'interval', seconds=3600)
scheduler.start()


class IndexListView(ListView):
    model = Blog
    template_name = 'mailing/index.html'
    context_object_name = 'objects_list'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = list(queryset)
        random.shuffle(queryset)
        return queryset[:3]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailings_count = len(Mailing.objects.all())
        mailings_is_active_count = len(Mailing.objects.filter(is_active=True))
        unique_clients_count = Client.objects.values('email').distinct().count()
        context['mailings_count'] = mailings_count
        context['mailings_is_active_count'] = mailings_is_active_count
        context['unique_clients_count'] = unique_clients_count
        return context


class MailingListView(ListView):
    model = Mailing
    template_name = 'mailing/mailing_list.html'
    context_object_name = 'objects_list'


class MailingCreateView(PermissionRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy('mailing:mailing_list')
    permission_required = 'mailing.add_mailing'

    def get(self, request, **kwargs):
        form = self.form_class(self.request.user, request.POST)
        context = {'form': form}
        return render(request, 'mailing/mailing_form.html', context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.user, request.POST)

        if form.is_valid():
            clients = form.cleaned_data.get('clients')
            if not clients:
                form.add_error('clients', 'Выберите хотя бы одного клиента.')
            mailing = form.save(commit=False)
            mailing.user = self.request.user
            mailing.save()
            form.save_m2m()
            return redirect(self.success_url)


class MailingUpdateView(PermissionRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingUpdateForm
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy('mailing:mailing_list')
    permission_required = 'mailing.change_mailing'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_form_class(self):
        if self.request.user.groups.filter(name='manager').exists():
            return MailingManagerUpdateForm
        else:
            return MailingUpdateForm


class MailingDetailView(DetailView):
    model = Mailing
    template_name = 'mailing/mailing_detail.html'


class MailingDeleteView(PermissionRequiredMixin, DeleteView):
    model = Mailing
    template_name = 'mailing/mailing_delete.html'
    success_url = reverse_lazy('mailing:mailing_list')
    permission_required = 'mailing.delete_mailing'


class ClientCreateView(PermissionRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client_form.html'
    success_url = reverse_lazy('mailing:client_list')
    permission_required = 'mailing.add_client'

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user = user
        client.save()
        return super().form_valid(form)


class ClientListView(PermissionRequiredMixin, ListView):
    model = Client
    template_name = 'mailing/client_list.html'
    context_object_name = 'objects_list'
    permission_required = 'mailing.view_client'


class ClientDetailView(DetailView):
    model = Client
    template_name = 'mailing/client_detail.html'


class ClientUpdateView(PermissionRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client_form.html'
    context_object_name = 'objects_list'
    success_url = reverse_lazy('mailing:client_list')
    permission_required = 'mailing.change_client'


class ClientDeleteView(PermissionRequiredMixin, DeleteView):
    model = Client
    template_name = 'mailing/client_delete.html'
    success_url = reverse_lazy('mailing:client_list')
    permission_required = 'mailing.delete_client'


class MailingLogListView(ListView):
    model = MailingLog
    template_name = 'mailing/mailing_log_list.html'
    context_object_name = 'objects_list'

mailing/templates/mailing/base.html
<!DOCTYPE html>
{% load static %}
{% load my_tags %}
<html lang="ru">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- INCLUDE CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">

    {% include 'mailing/includes/inc_mailing_menu.html' %}

</head>
<body>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailing/templates/mailing/catalog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block title %}
{{ object.title }}
{% endblock %}

{% block content %}
<br>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="cart-body">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h3 class="card-title">Вы хотите удалить продукт {{ object.product_name }} ?</h3>
                        <button><a type="submit" class="btn btn-danger">Удалить</a></button>
                        <button><a href="{% url 'catalog:index' %}" class="btn btn-warning">Отмена</a></button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

mailing/templates/mailing/client_delete.html
{% extends 'mailing/base.html' %}


{% block content %}
<br>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="cart-body">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h3 class="card-title">Вы хотите удалить клиента {{ object.fio }} ?</h3>
                        <button><a type="submit" class="btn btn-danger">Удалить</a></button>
                        <button><a href="{% url 'mailing:client_list' %}" class="btn btn-warning">Отмена</a></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}


{% block content %}
<br>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="cart-body">
                <div class="card-body">
                    <h3 class="card-title"> клиент: {{ object.fio }}</h3>
                    <div class=" mb-6"> почта: {{ object.email }}</div>
                    <div class=" mb-6"> комментарий: {{ object.comment }}</div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'mailing:client_list' %}" class="btn btn-outline-primary mb-2 align-center">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}
{% load my_tags %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-5">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">

                        {% if object %}
                        <h3>Изменить клиента</h3>
                        {% else %}
                        <h3>Добавить клиента</h3>
                        {% endif %}

                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
            </div>
        </div>
        <p>
            <button type="submit" class="btn btn-success">Сохранить</button>
            <button><a href="{% url 'mailing:client_list' %}" class="btn btn-warning">Отмена</a></button>
        </p>
    </form>
</div>
<br>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% load my_tags %}

<title>Клиенты</title>

<main role="main" class="inner cover">
    <h2 class="cover-heading">Список клиентов</h2>

    {% user_groups as user_group %}
    {% if perms.mailing.add_mailing %}
    <h3 class="card-title"><a class="btn btn-outline-primary" href="{% url 'mailing:client_create' %}">Создать нового
        клиента</a>
    </h3>
    {% endif %}

    <br>
</main>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-2">
    {% for object in objects_list %}
    {% if user == object.user %}
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ object.fio }}</h3>
            </div>
            <div class="card-footer">
                <div class=" mb-2"> почта: {{ object.email }}</div>
                <a class="mb-4"></a>
                <a class="btn btn-outline-primary " href="{% url 'mailing:client_detail' object.pk %}">Просмотр</a>
                <a class="btn btn-outline-primary " href="{% url 'mailing:client_update' object.pk %}">Редактировать</a>
                <a class="btn btn-outline-primary " href="{% url 'mailing:client_delete' object.pk %}">Удалить</a>
            </div>
        </div>
    </div>
    <br>
    {% endif %}
    {% endfor%}

</div>
{% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}
{% block content %}
{% load my_tags %}

<title>Главная</title>

<ul class="nav col-12 col-md-left  justify-content-left ">
    <li><a class="nav-link px-2">Всего рассылок: {{ mailings_count }}</a></li>
    <li><a class="nav-link px-4">Активных рассылок: {{ mailings_is_active_count }}</a></li>
    <li><a class="nav-link px-3">Уникальных клиентов в базе: {{ unique_clients_count }}</a></li>

</ul>

<main role="main" class="inner cover">
    <h2 class="cover-heading">Главная</h2>
</main>
<br>
{% include 'blogs/blog_include.html' %}

{% endblock %}

mailing/templates/mailing/mailing_delete.html
{% extends 'mailing/base.html' %}


{% block content %}
<br>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="cart-body">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h3 class="card-title">Вы хотите удалить рассылку {{ object.name }} ?</h3>
                        <button><a type="submit" class="btn btn-danger">Удалить</a></button>
                        <button><a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning">Отмена</a></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}


{% block content %}
<br>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="cart-body">
                <div class="card-body">
                    {{ form }}
                    <h3 class="mb-2">Название: {{ object.name }}</h3>
                    <p class="mb-2">Текст: {{ object.body }}</p>
                </div>
                <div class="card-footer">
                    {% if  object.is_active == True %}
                    <p class="mb-2">Активна</p>
                    {% else %}
                    <p class="mb-2">Неактивна</p>
                    {% endif %}
                    <p class="mb-2">{{ get_is_active }}</p>
                    <p class="mb-2">Статус: {{ object.get_status_display }}</p>
                    <p class="mb-2">Время старта: {{ object.time_start }}</p>
                    <p class="mb-2">Время окончания: {{ object.time_end }}</p>
                    <div class=" mb-2"> Периодичность: {{ object.get_periodicity_display }}</div>
                    {% if object.get_day_display != None %}
                    <p class="mb-2">Запуск каджого {{ object.get_day_display }} числа</p>
                    {% endif %}
                    {% if object..get_day_week_display != None %}
                    <p class="mb-2">Запуск каждый {{ object.get_day_week_display }}</p>
                    {% endif %}
                    <div class=" mb-6"> Автор: {{ object.user }}</div>
                    <input type="button" onclick="history.back();" value="Назад"/>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}
{% load my_tags %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-5">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        {% if object %}
                        <h3>Изменить рассылку</h3>
                        {% else %}
                        <h3>Добавить рассылку</h3>
                        {% endif %}
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {% manager_groups as manager_group %}
                    {% if user.groups.all.0 == manager_group %}
                    <div class="mb-3">
                        {{ form.is_active.label_tag }}{{ form.is_active }}
                    </div>
                    {% endif %}
                    <div class="mb-3">
                        {{ form.name.label_tag }}{{ form.name }}
                    </div>
                    <div class="mb-3">
                        {{ form.body.label_tag }}{{ form.body }}
                    </div>
                    <div class="mb-3">
                        {{ form.status.label_tag }}{{ form.status }}
                    </div>
                    <div class="mb-3">
                        {{ form.time_start.label_tag }}{{ form.time_start }}{{ form.time_start.help_text }}
                    </div>
                    <div class="mb-3">
                        {{ form.time_end.label_tag }}{{ form.time_end }}{{ form.time_end.help_text }}
                    </div>
                    <div class="mb-3">
                        {{ form.periodicity.label_tag }}{{ form.periodicity }}
                    </div>
                    <div class="mb-3">
                        {{ form.day.label_tag }}{{ form.day }}{{ form.day.help_text }}
                    </div>
                    <div class="mb-3">
                        {{ form.day_week.label_tag }}{{ form.day_week }}{{ form.day_week.help_text }}
                    </div>
                    <div class="mb-3">
                        {{ form.clients.label_tag }}{{ form.clients }}
                    </div>
                </div>
            </div>
        </div>
        <p>
            <button type="submit" class="btn btn-success">Сохранить</button>
            <button><a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning">Отмена</a></button>
        </p>
    </form>
</div>
<br>

{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% load my_tags %}

<title>Рассылки</title>

<main role="main" class="inner cover">
    <h2 class="cover-heading">Список рассылок</h2>

    {% if perms.mailing.add_mailing %}
    <h3 class="card-title"><a class="btn btn-outline-primary" href="{% url 'mailing:mailing_create' %}">Создать новую
        рассылку</a>
    </h3>
    {% endif %}
    <br>
</main>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in objects_list %}
    {% manager_groups as manager_group %}
    {% if user == object.user or user.groups.all.0 == manager_group %}
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ object.name }}</h3>
                {% if object.is_active == True %}
                <div class=" mb-2"> Активна </div>
                {% else %}
                <div class=" mb-2"> Неактивна </div>
                {% endif %}
            </div>
            <div class="card-body">
                <p class="card-text">{{ object.body|truncatechars:100 }}</p>
            </div>
            <div class="card-footer">
                <div class=" mb-2"> Автор: {{ object.user }}</div>
                <a class="mb-4"></a>
                <a class="btn btn-outline-primary " href="{% url 'mailing:mailing_detail' object.pk %}">Подробнее</a>
                {% if user == object.user or user.groups.all.0 == manager_group %}
                <a class="btn btn-outline-primary "
                   href="{% url 'mailing:mailing_update' object.pk %}">Редактировать</a>
                {% endif %}
                {% if user == object.user %}
                <a class="btn btn-outline-primary " href="{% url 'mailing:mailing_delete' object.pk %}">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
    <br>

</div>
{% endblock %}

mailing/templates/mailing/mailing_log_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% load my_tags %}

<title>Логи рассылок</title>

<main role="main" class="inner cover">
    <h2 class="cover-heading">Логи рассылок</h2>
    <br>
</main>

<div class="table">
    {% for object in objects_list %}
    {% manager_groups as manager_group %}
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h6 class="card-title">{{ object.time_try }}</h6>
            </div>
            <div class="card-body">
                <p class="card-text">Рассылка:  {{ object.mailing_current }}</p>
                {% if object.server_response %}
                <p class="card-text">Ответ сервера:  {{ object.server_response }}</p>
                {% endif %}
                {% if user == object.user %}
                <p class="card-text">клиент:  {{ object.client }}</p>
                {% endif %}
                <p class="card-text">Автор рассылки:  {{ object.user }}</p>
            </div>
            <div class="card-footer">
                <div class=" mb-2"> Статус рассылки:  {{ object.status }}</div>
                <a class="mb-4"></a>

            </div>
        </div>
    </div>
    <br>

    {% endfor%}

</div>
{% endblock %}

mailing/templates/mailing/no_choise_client.html
{% extends 'mailing/index.html' %}

{% block content %}
<div class="col-12">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <p>Выберите клиентов!</p>
                <input type="button" onclick="history.back();" value="Назад"/>
            </div>
        </div>
    </div>
</div>

{% endblock %}