blogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import BlogsConfig
from .views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogsConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('list', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import MailingConfig
from .views import MailingListView, MailingCreateView, ClientCreateView, MailingUpdateView, \
    MailingDeleteView, MailingDetailView, ClientListView, ClientDetailView, ClientUpdateView, ClientDeleteView, \
    IndexListView, MailingLogListView

app_name = MailingConfig.name

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('mailing_list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_detail/<int:pk>/', cache_page(60)(MailingDetailView.as_view()), name='mailing_detail'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_detail/<int:pk>/', cache_page(60)(ClientDetailView.as_view()), name='client_detail'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('mailing_log_list/', MailingLogListView.as_view(), name='mailing_log_list'),
    ]

blogs/models.py
from django.db import models

from config import settings
from mailing.utils import NULLABLE


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    body = models.TextField(verbose_name='содержимое')
    image = models.ImageField(verbose_name='изображение', **NULLABLE)
    date_of_creation = models.DateField(verbose_name='Дата создания', auto_now_add=True)
    views_count = models.IntegerField(default=0, verbose_name='просмотры')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь',
                             **NULLABLE)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

mailing/models.py
from datetime import datetime
from django.db import models
from config import settings
from mailing.utils import NULLABLE


class Client(models.Model):
    email = models.EmailField(verbose_name='электронная почта', unique=True)
    fio = models.CharField(max_length=100, verbose_name='ФИО')
    comment = models.TextField(verbose_name='комментарий')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь', **NULLABLE)

    def __str__(self):
        return f'{self.email}  {self.fio}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Mailing(models.Model):
    CHOICES_STATUS = (
        ('created', 'создана'),
        ('running', 'запущена'),
        ('completed', 'завершена'),
    )
    CHOICES_TIME = (
        ('day', 'раз в день'),
        ('week', 'раз в неделю'),
        ('mon', 'раз в месяц'),
    )
    CHOICES_DAYWEEK = (
        ('0', 'понедельник'),
        ('1', 'вторник'),
        ('2', 'среда'),
        ('3', 'четверг'),
        ('4', 'пятница'),
        ('5', 'суббота'),
        ('6', 'вскресенье'),
    )

    name = models.CharField(max_length=100, verbose_name='тема письма')
    body = models.TextField(verbose_name='тело письма')
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, verbose_name='статус', default='created')
    time_start = models.TimeField(verbose_name='начало времени отправки',
                                  help_text='Введите время в формате ЧЧ:ММ через двоеточие. Начало времени отправки '
                                            'должно быть раньше окончания времени отправки ')
    time_end = models.TimeField(verbose_name='окончание времени отправки',
                                help_text='Введите время в формате ЧЧ:ММ через  двоеточие. Начало времени отправки '
                                            'должно быть раньше окончания времени отправки ')
    periodicity = models.CharField(max_length=20, choices=CHOICES_TIME, verbose_name='периодичность')
    day = models.IntegerField(verbose_name='день', **NULLABLE,
                              help_text='Введите число при периодичности раз в месяц. Число должно быть от 1 до 31')
    day_week = models.CharField(max_length=15, choices=CHOICES_DAYWEEK, verbose_name='день недели', **NULLABLE,
                                help_text='Выберите день недели при периодичности раз в неделю')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='активность рассылки')
    clients = models.ManyToManyField("Client", related_name='clients', verbose_name='клиенты')

    def __str__(self):
        return f'{self.name}, {self.body}'

    class Meta:
        verbose_name = 'письмо'
        verbose_name_plural = 'письма'
        ordering = ['name', ]


class MailingLog(models.Model):
    STATUS_CHOICES = (
        ('1', 'Успешно'),
        ('0', 'Неуспешно'),
    )

    time_try = models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, verbose_name='статус попытки')
    server_response = models.TextField(verbose_name='ответ почтового сервера', **NULLABLE)
    client = models.CharField(max_length=150, verbose_name='клиент', **NULLABLE)
    mailing_current = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return f'Лог: "{self.mailing_current}"'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'
        ordering = ['-time_try', ]

blogs/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from blogs.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'image',)
    context_object_name = 'objects_list'
    success_url = reverse_lazy('blogs:list')

    def get_initial(self):
        return {'user': self.request.user}

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog
    context_object_name = 'objects_list'

    # def get_queryset(self, *args, **kwargs):
    #     queryset = super().get_queryset(*args, **kwargs)
    #     queryset = queryset.filter(is_published=True)
    #     return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body')
    success_url = reverse_lazy('blogs:list')


class BlogDeleteView(DeleteView):
    model = Blog
    template_name = 'blogs/blog_confirm_delete.html'
    success_url = reverse_lazy('blogs:list')

blogs/templates/blogs/blog_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block title %}
{{ object.title }}
{% endblock %}

{% block content %}
<br>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="cart-body">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h3 class="card-title">Вы хотите удалить блог {{ object.title }} ?</h3>
                        <p class="card-text">{{ object.body }}</p>
                        <button><a type="submit" class="btn btn-danger">Удалить</a></button>
                        <button><a href="{% url 'blogs:list' %}" class="btn btn-warning">Отмена</a></button>
                        <div class="card-footer">
                            Просмотры: {{ object.views_count }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blogs/templates/blogs/blog_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
{% load my_tags %}
<br>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="cart-body">
                <div class="card-body">
                    <h3 class="card-title">{{ object.title }}</h3>
                    <div class="card-body text-center">
                        <img src="{{ object.image|mediapath }}"/>
                    </div>
                    <p class="card-text">{{ object.body }}</p>
                </div>
                <div class="card-footer">
                    <div class=" mb-2"> Дата публикации: {{ object.date_of_creation }}</div>
                    <div class=" mb-2"> Автор: {{ object.user }}</div>
                    <div class=" mb-4"> Просмотры: {{ object.views_count }}</div>
                    <a href="{% url 'mailing:index' %}" class="btn btn-outline-primary mb-2 align-center">На главную</a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'blogs:list' %}" class="btn btn-outline-primary mb-2 align-center">К блогам</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blogs/templates/blogs/blog_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12  ">
    <div class="row">
        <div class="col-6 mt-4">
            <div class="card">
                <div class="cart-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                        <a class="btn btn-warning" href="{% url 'blogs:list' %}" >Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

blogs/templates/blogs/blog_include.html
{% load my_tags %}

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in objects_list %}
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ object.title }}</h3>
            </div>
            <div class="card-body">
                <div class="card-body text-center">
                    <img src="{{ object.image|mediapath }}"/>
                </div>
                <p class="card-text">{{ object.body|truncatechars:100 }}</p>
            </div>
            <div class="card-footer">
                <div class=" mb-2"> Дата публикации: {{ object.date_of_creation }}</div>
                <div class=" mb-2"> Просмотры: {{ object.views_count }}</div>
                <div class=" mb-2"> Автор: {{ object.user }}</div>
                <a class="mb-4"></a>
                <a class="btn btn-outline-primary " href="{% url 'blogs:view' object.pk %}">Читать</a>
            </div>
        </div>
    </div>
    <br>
    {% endfor%}
</div>

blogs/templates/blogs/blog_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% load my_tags %}


<title>Блоги</title>
<h2>Блоги</h2>
<br>
<form>
    {% if perms.mailing.add_mailing %}
    <a class="btn btn-outline-primary" href="{% url 'blogs:create' %}">Создать новый блог</a>
    {% endif %}
</form>
<br>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in objects_list %}
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ object.title }}</h3>
            </div>
            <div class="card-body">
                <p class="card-text">{{ object.body|truncatechars:100 }}</p>
            </div>
            <div class="card-footer">
                <div class=" mb-2"> Дата публикации: {{ object.date_of_creation }}</div>
                <div class=" mb-2"> Просмотры: {{ object.views_count }}</div>
                <div class=" mb-2"> Автор: {{ object.user }}</div>
                <a class="mb-4"></a>
                <a class="btn btn-outline-primary " href="{% url 'blogs:view' object.pk %}">Читать</a>
                {% if user == object.user %}
                <a class="btn btn-outline-primary " href="{% url 'blogs:edit' object.pk %}">Редактировать</a>
                <a class="btn btn-outline-primary " href="{% url 'blogs:delete' object.pk %}">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
    <br>
    {% endfor%}
</div>

{% endblock %}