blogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import BlogsConfig
from .views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogsConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('list', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .apps import UsersConfig
from .views import RegisterView, VerificationView, ErrorVerification, UserProfileView, UserManagerListView, \
    UserManagerProfileView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verification/', VerificationView.as_view(), name='verification'),
    path('verify_email/error/', ErrorVerification.as_view(), name='verify_email_error'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('users_list/', UserManagerListView.as_view(), name='users_list'),
    path('profile_manager/<int:pk>/', UserManagerProfileView.as_view(), name='profile_manager'),
    ]

users/models.py
import random

from django.contrib.auth.models import AbstractUser
from django.db import models

from mailing.utils import NULLABLE

default_code = ''.join([str(random.randint(0, 9)) for _ in range(12)])


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='активность пользователя',)
    email_verified = models.BooleanField(default=False, verbose_name='верификация почты')
    ver_code = models.CharField(max_length=15, default=default_code, verbose_name='код из письма')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f' {self.email}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from users.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email',  'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()
        self.fields['email'].disabled = True


class UserManagerForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('is_active',)

users/views.py
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, TemplateView, ListView

from config import settings
from users.forms import UserRegisterForm, UserProfileForm, UserManagerForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:verification')

    def form_valid(self, form):
        if form.is_valid():
            new_user = form.save()
            send_mail(
                subject='Подтверждение почты',
                message=f'Код {new_user.ver_code}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[new_user.email]
            )
        return super().form_valid(form)


class VerificationView(TemplateView):
    template_name = 'users/send_mail_code.html'

    def post(self, request):
        ver_code = request.POST.get('ver_code')
        user_code = User.objects.filter(ver_code=ver_code).first()

        if user_code is not None and user_code.ver_code == ver_code:
            user_code.is_active = True
            user_code.save()
            return redirect('users:login')
        else:
            return redirect('users:verification_email_error')


class ErrorVerification(TemplateView):
    template_name = 'users/verification_email_error.html'
    success_url = reverse_lazy('users:send_mail_code')


class UserProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('mailing:index')

    def get_object(self, queryset=None):
        return self.request.user


class UserManagerProfileView(UpdateView):
    model = User
    form_class = UserManagerForm
    template_name = 'users/manager_profile.html'
    success_url = reverse_lazy('users:users_list')


class UserManagerListView(ListView):
    model = User
    template_name = 'users/users_list.html'
    context_object_name = 'objects_list'

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-4"></div>
        <div class="col-5">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Вход
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
            </div>
            <br>
             <button type="submit" class="btn btn-success">Войти</button>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/manager_profile.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-4"></div>
        <div class="col-5">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Изменение активности пользователя {{ user }}
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.is_active }} : Активность пользователя

                </div>
            </div>
            <br>
             <button type="submit" class="btn btn-success">Подтвердить</button>
            <button><a href="{% url 'users:users_list' %}" class="btn btn-warning">Отмена</a></button>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-4"></div>
        <div class="col-5">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Регистрация
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
            </div>
            <br>
             <button type="submit" class="btn btn-success">Регистрация</button>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/send_mail_code.html
{% extends 'mailing/base.html' %}

{% block content %}
  <div class="col-12">
      <form class='row' method="post" enctype="multipart/form-data">
          <div class="col-4"></div>
          <div class="col-4">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                  Введите код
                </h4>
              </div>
              <div class="card-body">
                  {% csrf_token %}

                  <input type="text" name="ver_code" class="form-control" id="ver_code" required>
              </div>
              <div class="card-footer">
                  <button type="submit" class="btn btn-success">Подтвердить</button>
              </div>
            </div>
          </div>
      </form>
  </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-4"></div>
        <div class="col-5">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Профиль
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
            </div>
            <br>
             <button type="submit" class="btn btn-success">Сохранить</button>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/users_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% load my_tags %}

<title>Пользователи</title>

<h2>Пользователи</h2>
<br>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% user_groups as user_group %}
    {% for object in objects_list %}
    {% if object.groups.all.0 == user_group %}
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ object.email }}</h3>
            </div>
            <div class="card-footer">
                <a class="mb-4"></a>
                <a class="btn btn-outline-primary " href="{% url 'users:profile_manager' object.pk %}">
                    {% if object.is_active %}
                    Заблокировать
                    {% else %}
                    Разблокировать
                    {% endif %}</a>
            </div>
        </div>
    </div>
    {% endif %}
    <br>
    {% endfor%}
</div>

{% endblock %}

users/templates/users/verification_email_error.html
{% extends 'mailing/base.html' %}

{% block content %}
  <div class="col-12">
      <form class='row' method="post" enctype="multipart/form-data">
          <div class="col-4"></div>
          <div class="col-4">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                  Неверный код
                </h4>
              </div>
              <div class="card-body">
              </div>
              <div class="card-footer">
                  <a href="{% url 'users:verification_email' %}" class="btn btn-success">Повторить попытку</a>
              </div>
            </div>
          </div>
      </form>
  </div>
{% endblock %}